#--------------------------------------------------------------
# Poratiner docker-compose
#--------------------------------------------------------------
version: '3'

#---NETWORKS---------------------------------------------------
networks:
  default:
    external:
      name: common

#---VOLUMES ---------------------------------------------------
volumes:
  data:
    
#---SERVICES---------------------------------------------------
services:
  svnedge:
    image: 'mamohr/subversion-edge:latest'
    ports:
      - '18080:18080'
      - '3343:3343'
      - '4434:4434'
    volumes:
      - 'data:/opt/csvn/data'
