#--------------------------------------------------------------
# Jenkins docker-compose
#--------------------------------------------------------------
version: '3'

#---NETWORKS---------------------------------------------------
networks:
  default:
    external:
      name: common

#---VOLUMES ---------------------------------------------------
volumes:
  data:
    driver: convoy

#---SERVICES---------------------------------------------------
services:
  jenkins:
    build:
      context: "./jenkins"
      dockerfile: "Dockerfile"
    ports:
      - '50000:50000'
      - '8081:8080'
    volumes:
      - 'data:/opt/jenkins_home'
    environment:
      JAVA_OPTS: -Duser.timezone=Asia/Tokyo
      JENKINS_OPTS: --sessionTimeout=1440
